### PR TITLE
Setup gradle build & add SonarQube

### PR DESCRIPTION
**Pull request by Moonlander1**
Part of: #1 
Fixes: #6 
Fixes: #8 
Base branch set to master to see if SonarAnalysis report will run. 
- [x] Added gradle build
- [x] Added Sonar 
- [x] Create github actions yaml
- [x] Run gradle build on every PR 
- [x] Run SonarQube Analysis on every master push (Free package can only analyze master)

Sonar link: https://sonarcloud.io/project/overview?id=iet-homework_iet-homework-not-meta

### CODE REVIEW

**Comment by Moonlander1** [comment]
BEFORE MERGE:  filter out the garbage gradle files and add them to gitignoe

**Comment by Moonlander1** [comment]
Steps to run sonar locally (tho it serves no real porpuse) 
- Generate sonar token 
- When running the sonarqube task add `SONAR_TOKEN=*generated token*` as an environmental variable 
- Enjoy

**Review by GuTory — CHANGES_REQUESTED** [review]
please add this to the build.gradle.kts file so the compiled jar can be run:

`tasks.withType<Jar>{
    manifest {
        attributes["Main-Class"] = "Main"
    }
}`

**Comment by Moonlander1** [comment]
> please add this to the build.gradle.kts file so the compiled jar can be run:
> 
> `tasks.withType<Jar>{ manifest { attributes["Main-Class"] = "Main" } }`

It has been pushed to the branch, but during the time github was down, so it does not show up on the PR. You can see the commit here: 
https://github.com/BME-MIT-IET/iet-hf-2023-notmeta/commit/83e61a5c7b542b5426331cda79e0ef6ff904d49c

**Review by NyistMilan — APPROVED** [review]
Tested everything locally. LGTM

**Review by GuTory — APPROVED** [review]

**Pull request merged**
